global using MTKDotNetCore.AdoDotNetCustomService.Shared;
global using System.Data.SqlClient;
global using Newtonsoft.Json;
global using static MTKDotNetCore.AdoDotNetCustomService.Shared.AdoDotNetService;
global using System.Data;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore;
global using MTKDotNetCore.AdoDotNetCustomService.Model;
global using Microsoft.AspNetCore.Mvc;
